#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  "#4D4D4D"
bspc config focused_border_color "#8BE9FD"

bspc rule -a Emacs state=tiled follow=on

xsetroot -cursor_name left_ptr
feh --bg-scale ~/.config/wallpaper.jpg
